--?
CREATE TRIGGER trg_log_plano
AFTER INSERT OR UPDATE OR DELETE
ON plano
FOR EACH ROW
EXECUTE FUNCTION log_plano_func();


CREATE TRIGGER trg_log_tour_virtual
AFTER INSERT OR UPDATE OR DELETE
ON tour_virtual
FOR EACH ROW
EXECUTE FUNCTION log_tour_virtual_func();


CREATE TRIGGER trg_log_eventos
AFTER INSERT OR UPDATE OR DELETE
ON eventos
FOR EACH ROW
EXECUTE FUNCTION log_eventos_func();

